import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={`p-4 ${inter.className}`}>
          <header className="text-lg p-4 border-b-2">
            <div className="flex gap-2">
              <Link href="/" className="underline text-blue-500">
                Home
              </Link>
              <Link href="/about" className="underline text-blue-500">
                About
              </Link>
              <Link href="/todos" className="underline text-blue-500">
                Todos
              </Link>
            </div>
          </header>
          <main className="p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
